### ISSUE TITLE
Refactor DOCX extraction to use fast-xml-parser and fflate instead of Mammoth

### ISSUE THREAD

**Issue by xichen-ansearch** [A-star-logic/memoire#54]
Hi,

I’ve finished refactoring the extraction of Word documents based on fast-xml-parser and fflate instead of Mammoth, and now it only outputs raw text. I followed the approach from Ansearch’s code, and everything’s working fine with smaller files.

For context, I also tested the performance of Mammoth-based file parsing with different file sizes. One issue I encountered with both Mammoth and my implementation is when a single document.xml file from the DOCX becomes too large. This triggers the **"Cannot create a string longer than 0x1fffffe8 characters"** error, which occurs because both Mammoth and my code attempt to read the entire document into memory as one large string. When dealing with very large files, this exceeds the maximum string size allowed in JavaScript.

However, if the DOCX file consists of multiple smaller document.xml files (even if the total file size is large), my code is still able to process it more efficiently and faster than Mammoth. This is because Mammoth treats the whole DOCX as a single large document, while my code can handle large documents with multiple smaller XML parts without running into memory limitations.

When testing with a very large 500MB DOCX file, I ran into some performance issues. It took about 160 seconds to process on my local machine, which is a bit slow. The main difference I found is that Ansearch’s code uses **yauzl** for unzipping, which supports streaming. This means **yauzl** can handle large files more efficiently because it processes the file in chunks as it’s being read, rather than loading the entire file into memory at once. On the other hand, my current implementation uses **fflate** for unzipping the DOCX file, which doesn’t support streaming by default. Essentially, **fflate** extracts the entire ZIP file into memory at once, which can be slow for large files unless custom streaming functionality is implemented to replicate **yauzl**'s streaming capabilities.

Considering the preference for libraries with minimal dependencies and full JavaScript support (with future compatibility for Deno), **yauzl** may not be the best fit as it doesn't fully align with these requirements. **yauzl** relies on native dependencies, which are not directly compatible with Deno. On the other hand, **fflate** is lightweight and works well for the goal of using pure JavaScript. Given these trade-offs, would it be preferable to continue using **fflate**, or should I explore other potential solutions?

Thanks!

**Comment by Mael-Abgrall** [comment]
using fflate is better, as said, because it will make it easier to move to deno if/when we want.

On the streaming, I recall they were speaking about it on the readme of the package, so it's possible. Although, right now I would rather focus on supporting all document types rather than ultra-large documents.

The file is unlikely going to be that large ([this thread let me think the text cannot be larger than 32mb and the whole document limited to 512mb](https://answers.microsoft.com/en-us/msoffice/forum/all/word-file-size-limit-of-32-megabytes-512-mb/2dfd68ed-691f-48a2-966f-d6ad34e1a7a0)). However the performance increase thanks to streams is a good thing.

As we will discuss in our minutes today, focus on supporting all kind of office and libre office documents first, then optimise the parsing second
