### ISSUE TITLE
Better reranking

### ISSUE THREAD

**Issue by Mael-Abgrall** [A-star-logic/memoire#60]
The issue of RRF currently is that when documents with low relevancy are in the results, they can skew or pollute the results.

This is because RRF has too much emphasis on the position of documents, which is counterproductive when the said documents are not related to the query (eg: query about carrots, results contain finance documents).

Some ideas on how to improve RRF (first) would be to remove low-score documents before doing the reranking (ex: remove any documents from the vector search with a score lower than 0.3, and remove any documents from the full-text search with a score lower than 0.3)

You could also look into improving the math behind RRF, but I think filtering low score is already a big step in improving the results

Additionally, __ONLY once this is done__, you could have a look into better reranking techniques that will improve the results at the expense of speed (ex: using AI to rerank)

**Comment by sriram-vinnakota** [comment]
The issue is because normalization is not done for FTS score, the scores doesn't bound  to 0-1 range unlike vector search, so we have to normalize, or else we would be doing  FTS alone most of the times in hybrid search, that's because the FTS score might be more than 1 and vector score is less than 1, and I suggest not to filter out the score, because
1. there might the possibility that the vector score with 0.2 might have FTS score 1 and vice-versa, if we ignore, statement with low scores in both the searchs might appear on top in the final result
